baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Sameena Koirala'
theme = 'ananke'

[[menu.main]]
name = "Resume"
url = "/resume"
title = "Resume page"
weight = 1

[[menu.main]]
name = "Contact"
url = "/contact"
title = "Contact page"
weight = 2
